import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/tailwind.css';
import { AuthProvider } from '@/features/auth';
import { getUser } from '@/features/auth/api/server/getUser';
import { cookies } from 'next/headers';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser(cookies());

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider user={user!}>
          <div className="grid place-content-center h-dvh">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
